project:
 type: website
 
website:
 site-url: culverjamie.github.io/j-datsci/
 title: "Data Science Blog"
 description: "DAT303 Final Project and Portfolio"
 navbar:
   right:
   - about.qmd
   - icon: github
     href: https://github.com/culverjamie/
   - icon: linkedin
     href: https://linkedin.com/in/jamie-culver-a924a12aa/
format:
 html:
   theme: cosmo
   css: styles.css
